# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-26 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191125_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=600),
        ),
    ]
