# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-22 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='feed',
            name='images',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
