# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-22 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191122_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.PositiveIntegerField(choices=[(1, 'EUR'), (2, 'USD'), (3, 'HUF')], default=1),
        ),
    ]
