# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-25 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.PositiveIntegerField(choices=[(1, 'EUR'), (2, 'USD'), (3, 'HUF')], default='1'),
        ),
    ]
