# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-25 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191125_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EURO'), ('USD', 'USA dollar'), ('HUF', 'Hungarian Forint')], default='EUR', max_length=3),
        ),
    ]
