# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-25 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20191125_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('HUF', 'HUF')], default='EUR', max_length=3),
        ),
    ]
