# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-25 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191125_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(default='€', max_length=1),
        ),
    ]
