# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-25 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='review',
        ),
    ]
