# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-02 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20191125_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='', max_length=256),
        ),
    ]
