# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-02 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='type_id',
        ),
    ]
