# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-25 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20191202_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description_section_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='description_section_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='description_section_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='description_section_4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='description_section_5',
            field=models.TextField(default=''),
        ),
    ]
