# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-25 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20191225_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_section_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_section_5',
        ),
    ]
